from ursina import load_texture

cursor_texture = load_texture("assets/textures/cursor.png")
model_texture = load_texture("assets/textures/models_texture.png")
none_texture = load_texture("no texture found.fuckit")


blocks = ["stone", 
"weathered copper block", 
"crimson wood", 
"dark oak vertical", 
"birch vertical", 
"acacia vertical", 
"crimson vertical", 
"mangrove vertical", 
"spruce vertical", 
"warped vertical", 
"jungle vertical", 
"dark oak horisontal", 
"birch horisontal", 
"acacia horisontal", 
"crimson horisontal", 
"mangrove horisontal", 
"spruce horisontal", 
"warped horisontal", 
"jungle horisontal", 
"flowering azalea leaves", 
"dark oak wood", 
"birch wood", 
"acacia wood", 
"crismon wood", 
"jungle wood",
"mangrove wood", 
"spruce wood", 
"warped wood", 
"quartz bricks", 
"crimson wart", 
"warped wart", 
"birch leaves", 
"spruce leaves", 
"jungle leaves", 
"mangrove leaves", 
"azalea leaves", 
"acacia leaves", 
"dark oak leaves", 
"deepslate coal ore", 
"deepslate copper ore", 
"deepslate iron ore", 
"deepslate gold ore", 
"deepslate lapis ore", 
"deepslate redstone ore", 
"deepslate emerald ore",
"deepslate diamond ore",  
"deepslate bricks", 
"cracked deepslate tiles",  
"cracked deepslate bricks",  
"deepslate",  
"oak wood", 
"magma", 
"purpur block", 
"amethyst", 
"dirt", 
"spawner", 
"sponge", 
"oak vertical", 
"water", 
"stone brick", 
"diorite smooth", 
"andesite smooth", 
"granite smooth", 
"nether gold ore", 
"red nether bricks", 
"redstone ore", 
"redstone block", 
"sand", 
"red sand",  
"oxidized copper block", 
"quartz ore", 
"nether bricks", 
"netherite block", 
"oak leaves", 
"moss", 
"mossy stone bricks", 
"mossy cobblestone",  
"oak horisontal", 
"lava", 
"lapis block", 
"lapis ore", 
"obsidian", 
"quartz", 
"netherrack", 
"iron ore", 
"iron ore block", 
"iron block", 
"grass", 
"granite", 
"gravel", 
"glass",  
"endstone", 
"exposed copper block", 
"gold ore block", 
"gold block", 
"gold ore", 
"endstone bricks", 
"emerald block", 
"emerald ore",  
"diorite", 
"crying obsidian",  
"diamond block", 
"diamond ore", 
"andesite", 
"bedrock", 
"chiseled nether bricks", 
"bricks", 
"coal block", 
"coal ore", 
"cobblestone", 
"copper block", 
"copper ore block", 
"copper ore", 
"cracked nether bricks"]


blocks_textures = {}
for block in blocks:
    blocks_textures[block] = load_texture(f"assets/textures/blocks/{block}.png")